# use ubuntu:20.04 as the base image
FROM ubuntu:20.04 

# copy script from the current directory on the host to /root of container
COPY ./script.sh /root/

# run the script on startup
CMD ["/root/script.sh"]